version: '2.1'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4567-4584:4567-4584"
      - "${LS_PORT_WEB_UI-8080}:${LS_PORT_WEB_UI-8080}"

    environment:
      - SERVICES=${LS_SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=${LS_PORT_WEB_UI- }
      - DOCKER_HOST=unix:///var/run/docker.sock

    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
